apiVersion: v1
kind: Service
metadata:
  name: mypipeline
  namespace: namespace-workflow-1714849690605
spec:
  type: LoadBalancer
  selector:
    app: mypipeline
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000